let types = {
  // root mutations
  showSpinner: 'showSpinner',
  showSnackbar: 'showSnackbar',
  setUpdateProperty: 'setUpdateProperty',
  catalogBack: 'catalogBack',
  categoryBack: 'categoryBack',

  // USERDATA
  USER_DATA: 'USER_DATA',
  R_USER_DATA: 'R_USER_DATA',

  // ENTITY and currentENTITY mutations
  UPDATE_ENTITIES: 'UPDATE_ENTITIES',
  ADD_ENTITY: 'ADD_ENTITY',
  UPDATE_ENTITY: 'UPDATE_ENTITY',
  DELETE_ENTITY: 'DELETE_ENTITY',
  CURRENT_ENTITY: 'CURRENT_ENTITY',
  UPDATE_ENTITY_SCHEMAS: 'UPDATE_ENTITY_SCHEMAS',
  UPDATE_ENTITY_SCHEMA: 'UPDATE_ENTITY_SCHEMA',
  UPDATE_UPDATE_ENTITY: 'UPDATE_UPDATE_ENTITY',

  // CATALOG and currentCATALOG mutations
  UPDATE_CATALOGS: 'UPDATE_CATALOGS',
  ADD_CATALOG: 'ADD_CATALOG',
  UPDATE_CATALOG: 'UPDATE_CATALOG',
  DELETE_CATALOG: 'DELETE_CATALOG',
  CURRENT_CATALOG: 'CURRENT_CATALOG',
  UPDATE_CATALOG_SCHEMAS: 'UPDATE_CATALOG_SCHEMAS',
  UPDATE_CATALOG_SCHEMA: 'UPDATE_CATALOG_SCHEMA',
  UPDATE_UPDATE_CATALOG: 'UPDATE_UPDATE_CATALOG',

  // FACTORY and currentFACTORY mutations
  UPDATE_FACTORIES: 'UPDATE_FACTORIES',
  ADD_FACTORY: 'ADD_FACTORY',
  UPDATE_FACTORY: 'UPDATE_FACTORY',
  DELETE_FACTORY: 'DELETE_FACTORY',
  CURRENT_FACTORY: 'CURRENT_FACTORY'
}

export default types
