export default [
  {link: 'adminSettings', additional: [{link: 'routeAdminGeneral', requestParams: ['user_id']}]},
  {link: 'areaCatalog'},
  {link: 'attachments', additional: [{link: 'attachmentsInfo', requestParams: ['attachments_ids']}]},
  {link: 'brandsCatalog'},
  {link: 'cityCatalog', additional: [{link: 'cityCatalogByArea', requestParams: ['user_id', 'area_id']}]},
  {link: 'clientAddresses', additional: [{link: 'clientAddressesByClient', requestParams: ['user_id', 'client_id']}]},
  {link: 'clientInfo', additional: [{link: 'clientInfoByClient', requestParams: ['user_id', 'client_id']}]},
  {link: 'clientTypes'},
  {link: 'clients', additional: [{link: 'routeAdminClients', requestParams: ['user_id']}]},
  {link: 'currencyCatalog'},
  {link: 'events'},
  {link: 'log', additional: [{link: 'routeAdminLogs', requestParams: ['user_id']}]},
  {link: 'messageContents'},
  {link: 'messages', additional: [{link: 'messagesByMessageContent', requestParams: ['user_id', 'message_content_id']}]},
  {link: 'orderPositionStates'},
  {link: 'orderPositions', additional: [{link: 'orderPositionsByOrders', requestParams: ['user_id', 'order_id']}]},
  {link: 'orderStates'},
  {link: 'orders', additional: [{link: 'routeOrders', requestParams: ['user_id', 'state_id']}]},
  {link: 'partnersCatalog'},
  {link: 'productCategories', additional: [{link: 'productsCategoriesByProductCategory', requestParams: ['user_id', 'category_id']}]},
  {link: 'productComments', additional: [{link: 'routeCatalogProductsComments', requestParams: ['user_id', 'product_id']}]},
  {link: 'products',
    additional: [{link: 'productsByProductCategory', requestParams: ['user_id', 'category_id']},
      {link: 'routeCatalogProductsGeneral', requestParams: ['user_id', 'product_id']},
      {link: 'productsRecommendationsCatalog', requestParams: ['user_id']}
    ]},
  {link: 'productCategoryPositions', additional: [{link: 'productCategoryPositionsByCategory', requestParams: ['user_id', 'category_id']}]},
  {link: 'productsPositions', additional: [{link: 'productsPositionsByCategory', requestParams: ['user_id', 'category_id']}]},
  {link: 'settings', additional: [{link: 'routeAdminSettings', requestParams: ['user_id']}]},
  {link: 'unitCatalog'},
  {link: 'userCartPositions'},
  {link: 'userCartStates'},
  {link: 'userCarts'},
  {link: 'userInfo'},
  {link: 'userLogins'},
  {link: 'userRoleRoutes'},
  {link: 'userRoles'},
  {link: 'users'},
  {link: 'viewSettings', additional: [{link: 'routeViewSettings', requestParams: ['user_id']}]},
  {link: 'routeCatalogProductsRecommendations', requestParams: ['user_id', 'product_id']},
  {link: 'userBonuses', additional: [{link: 'userBonusesDetails', requestParams: ['user_id']}]}
]
