export default [
  {link: 'adminSettings'},
  {link: 'attachments'},
  {link: 'brandsCatalog'},
  {link: 'clientAddresses'},
  {link: 'clientInfo'},
  {link: 'clientTypes'},
  {link: 'clients'},
  {link: 'currencyCatalog'},
  {link: 'log'},
  {link: 'orderPositionStates'},
  {link: 'orderPositions'},
  {link: 'orderStates'},
  {link: 'orders'},
  {link: 'partnersCatalog'},
  {link: 'productCategories'},
  {link: 'products'},
  {link: 'unitCatalog'},
  {link: 'settings'}
]
